### ISSUE TITLE
No Class Def Found Error

### ISSUE THREAD

**Issue by bobaikato** [imagekit-developer/imagekit-java#11]
Hey, nothing working here.

```java
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/RequestBody
	at io.imagekit.sdk.ImageKit.getInstance(ImageKit.java:30)
	at com.techgeeknext.SpringBootUploadImageApplication.main(Aopp.java:16)
Caused by: java.lang.ClassNotFoundException: okhttp3.RequestBody
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 2 more
```

**Comment by bobaikato** [comment]
I think similar issue #3 
When are you resolving this issue? Your tool is useless to us without this fix.

**Comment by ryokuu** [comment]
if u are working with maven project, i fixed the error by adding this maven dependency 

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.9.1</version>
        </dependency>
