### ISSUE TITLE
ImageKit instantiation error

### ISSUE THREAD

**Issue by Hadit1993** [imagekit-developer/imagekit-java#29]
Hi.
I went along with documentaion and added config.properties in my resource folder and added public and private keys and url endpont there.
and here is my imagekit instantiation: 

```
@SpringBootApplication
class EShopBackApplication

fun main(args: Array<String>) {
    
    runApplication<EShopBackApplication>(*args)
	val imageKit = ImageKit.getInstance()
	val config = Utils.getSystemConfig(EShopBackApplication::class.java)
	imageKit.config = config
}
```

When I run the app I got this error: 

```
Exception in thread "main" java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:70)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.kt:1073)
	at io.imagekit.sdk.tasks.RestClient.<init>(RestClient.java:60)
	at io.imagekit.sdk.ImageKit.getInstance(ImageKit.java:40)
	at com.hadit1993.eshopback.EShopBackApplicationKt.main(EShopBackApplication.kt:16)
```

What is the problem?

**Comment by Ox0017** [comment]
Problem is the required dependency `com.squareup.okhttp3:okhttp:3.10.0` (from 2018)
You are probably using a newer okhttp version in your project through spring.

**Comment by Pradeep7976** [comment]
**Still not fixed ??**
7 months

**Comment by NoonieBao** [comment]
problem still......however, as 0x00117 say, i add the okhttp dependency, now it work well.

```
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.10.0</version>
        </dependency>
```

```java
            ImageKit imageKit = ImageKit.getInstance();

            Configuration config = new Configuration(your_public_key, your_private_key, your_url_endpoint);
            imageKit.setConfig(config);

            
            byte[] bytes1 = file.getBytes();
            FileCreateRequest fileCreateRequest = new FileCreateRequest(
                    bytes1,           //  required, "binary", "base64" or "file url"
                    "sample-image11.jpg"    //  required
            );
            Result resultt = imageKit.upload(fileCreateRequest);
            System.out.println(resultt);
```

**Comment by Hadit1993** [comment]
@NoonieBao I recommend you not using this library in real projects. it's obvious that this repository is not maintained properly and in the future you may get dependency version conflict errors.

**Comment by NoonieBao** [comment]
> @NoonieBao I recommend you not using this library in real projects. it's obvious that this repository is not maintained properly and in the future you may get dependency version conflict errors.

Good tips, thanks! It is only being used for my personal project, and I have made a backup for unexpected conflicts.

**Comment by imagekitio** [comment]
This issue has been resolved in version 3.0.0.

The SDK now uses OkHttp 4.12.0, eliminating the dependency conflict that caused the `NoSuchFieldError: Companion` error.

The complete rewrite in Kotlin with modern dependencies ensures compatibility with current Spring Boot and framework versions.

Closing as fixed.
